# Copy this file to local.toml to make changes for a version that git will ignore.
[redis]
host = "127.0.0.1"
port = "6379"
path = "" # path to unix socket, use this over host/port if you can.
password = ""
db = "" # database number

[world]
id = 1017 # world member has to be on to get in role, and default world for wvw stuffs.
role = "" # Name of the role, leave blank if you don't want this

[guild]
id  = "" # Guild unique ID in format XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX, this can be found at https://api.guildwars2.com/v2/guild/search?name=[guild name]
key = "" # API Key from top guild rank with the "guilds" permission
member_role = "" # Name of the role guild members go in
motd_channel = "" # Will set the channel description to the guild motd
motd_convert_urls = true # Convert urls from the motd that don't start with http:// to actual urls that discord parses to a link
motd_excluded_subdomains = [ # An array of url subdomains in regular expressions of which the url should not be converted
  "[^\\.]*ts[^\\.]*", # *ts*.example.com
  "[^\\.]*teamspeak[^\\.]*" # *teamspeak*.example.com
]

[discord]
clientid = "" # Used to generate a link to add the bot to a server
token = "" # Token for your discord bot user

[features]
enabled = ["ranks", "motd", "wvw_score"]
